Repository sweetyrdf/easyrdf, pull requests merged in 2020-06, with the labels that each got.

#11 ntriples and turtle parser and serialised fixes
  lib/Parser/Ntriples.php
  lib/Parser/Turtle.php
  lib/Serialiser/Ntriples.php
  lib/Serialiser/Turtle.php
  test/EasyRdf/GraphTest.php
  test/EasyRdf/Parser/NtriplesTest.php
  test/EasyRdf/Serialiser/NtriplesArray.php
  test/EasyRdf/Serialiser/NtriplesTest.php
  test/EasyRdf/Serialiser/TurtleTest.php
  test/fixtures/foaf.nt
Labels: bugfix, enhancement

#13 Attempt(s) to fix timeouts during test runs
  lib/Http/Client.php
Labels: enhancement

#16 Fixes #15 (XML parser converts plus signs into spaces)
  lib/Parser/RdfXml.php
  test/EasyRdf/Parser/RdfXmlTest.php
  test/fixtures/rdfxml/issue15.rdf
Labels: bugfix

#18 Graph::properties() and Resource::properties() methods handle properties in unknown namespaces properly.
  lib/Graph.php
  test/EasyRdf/ResourceTest.php
Labels: bugfix
